const mongoose = require("mongoose");

const relatedContentSchema = new mongoose.Schema(
  {
    sourceType: {
      type: String,
      enum: ["city", "route", "service", "vehicle", "tour", "destination", "blog", "cms-page", "homepage"],
      required: true
    },
    sourceId: { type: String, default: "", trim: true },
    sourceSlug: { type: String, default: "", trim: true },
    relatedType: {
      type: String,
      enum: ["city", "route", "service", "vehicle", "tour", "destination", "blog"],
      required: true
    },
    relatedId: { type: String, default: "", trim: true },
    relatedSlug: { type: String, default: "", trim: true },
    label: { type: String, default: "", trim: true },
    sortOrder: { type: Number, default: 0 },
    autoGenerated: { type: Boolean, default: false }
  },
  { timestamps: true }
);

relatedContentSchema.index({ sourceType: 1, sourceSlug: 1 });

const RelatedContent = mongoose.model("RelatedContent", relatedContentSchema);

module.exports = { RelatedContent };
